name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2
        with:
          runtime: node@24
          cache: true
          install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
